SELECT A.ID, (CASE
           WHEN A.PER <= 0.25 THEN 'LOW'
           WHEN A.PER <= 0.5 THEN 'MEDIUM'
           WHEN A.PER <= 0.75 THEN 'HIGH'
           WHEN A.PER <= 1 THEN 'CRITICAL'
           END) AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS PER
      FROM ECOLI_DATA) A
ORDER BY A.ID