SELECT C.ID, (SELECT FISH_NAME
             FROM FISH_NAME_INFO D
             WHERE C.FISH_TYPE = D.FISH_TYPE) AS FISH_NAME, C.LENGTH
FROM (SELECT FISH_TYPE, MAX(LENGTH) AS MAX
FROM FISH_INFO A
GROUP BY FISH_TYPE) B
LEFT JOIN FISH_INFO C ON B.FISH_TYPE = C.FISH_TYPE AND B.MAX = C.LENGTH
ORDER BY ID

