SELECT N.BOOK_ID, N.AUTHOR_NAME, DATE_FORMAT(N.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM (SELECT B.BOOK_ID, A.AUTHOR_NAME, B.PUBLISHED_DATE, B.CATEGORY
    FROM BOOK B JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
    ) N
WHERE N.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE